/**
 * Common names that do not match an identifier on their own: "Next.js" is the
 * npm package `next`, "Postgres" is the product postgresql/postgresql. Keys
 * are normalizeKey() output. A name with several entries is offered as a
 * choice. Contributions welcome: keep entries to identifiers that appear in
 * CVE records or advisories.
 */
export const ALIASES: Record<string, string[]> = {
  next: ['npm:next'],
  next_js: ['npm:next'],
  nextjs: ['npm:next'],
  react: ['npm:react'],
  express: ['npm:express'],
  express_js: ['npm:express'],
  angular: ['npm:@angular/core'],
  vue: ['npm:vue'],
  vue_js: ['npm:vue'],
  nuxt: ['npm:nuxt'],
  django: ['pypi:django'],
  flask: ['pypi:flask'],
  fastapi: ['pypi:fastapi'],
  rails: ['gem:rails'],
  ruby_on_rails: ['gem:rails'],
  laravel: ['composer:laravel/framework'],
  symfony: ['composer:symfony/symfony'],
  spring: ['maven:org.springframework:spring-core'],
  spring_framework: ['maven:org.springframework:spring-core'],
  spring_boot: ['maven:org.springframework.boot:spring-boot'],
  log4j: ['maven:org.apache.logging.log4j:log4j-core'],
  postgres: ['p:postgresql/postgresql'],
  postgresql: ['p:postgresql/postgresql'],
  mysql: ['p:oracle/mysql'],
  mariadb: ['p:mariadb/mariadb'],
  mongodb: ['p:mongodb/mongodb'],
  redis: ['p:redis/redis'],
  nginx: ['p:f5/nginx', 'p:nginx/nginx'],
  apache: ['p:apache/http_server'],
  httpd: ['p:apache/http_server'],
  apache_httpd: ['p:apache/http_server'],
  tomcat: ['p:apache/tomcat'],
  kubernetes: ['p:kubernetes/kubernetes'],
  k8s: ['p:kubernetes/kubernetes'],
  node: ['p:nodejs/node_js'],
  node_js: ['p:nodejs/node_js'],
  nodejs: ['p:nodejs/node_js'],
  openssl: ['p:openssl/openssl'],
  openssh: ['p:openbsd/openssh'],
  wordpress: ['p:wordpress/wordpress'],
  jenkins: ['p:jenkins/jenkins'],
  gitlab: ['p:gitlab/gitlab'],
  grafana: ['p:grafana/grafana'],
  ios_xe: ['p:cisco/ios_xe'],
  cisco_ios_xe: ['p:cisco/ios_xe'],
  fortigate: ['p:fortinet/fortios'],
  fortios: ['p:fortinet/fortios'],
  exchange: ['p:microsoft/exchange_server'],
  microsoft_exchange: ['p:microsoft/exchange_server'],
  vcenter: ['p:vmware/vcenter_server'],
  confluence: ['p:atlassian/confluence_data_center', 'p:atlassian/confluence_server'],
  jira: ['p:atlassian/jira_data_center', 'p:atlassian/jira_server'],
};
