/**
 * Refreshes test/fixtures/injection/corpus.json: real prompt-injection and
 * jailbreak text, for measuring the phrase screen in src/resolve/injection.ts.
 *
 *   npm run update-injection-corpus
 *
 * Sources are pinned to commits so the test's numbers only move when this is
 * re-run on purpose. To update, change a commit below, re-run, and adjust the
 * recall floors in test/injection.test.ts to the new measurement.
 *
 * - garak (Apache-2.0): in-the-wild jailbreaks and the DAN family.
 * - PayloadsAllTheThings (MIT): the Prompt Injection page's example payloads.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { USER_AGENT } from '../src/config';

const GARAK_COMMIT = 'bb30a7e79f4e78ef633a92295f142105a0e69941';
const PATT_COMMIT = '3ac27901c711bdf3f5b65a7b1d1820a1f65bd09a';
const GARAK = `https://raw.githubusercontent.com/NVIDIA/garak/${GARAK_COMMIT}/garak/data`;
const PATT = `https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/${PATT_COMMIT}/Prompt%20Injection/README.md`;
const DAN_FILES = [
  'AntiDAN', 'ChatGPT_Developer_Mode_RANTI', 'ChatGPT_Developer_Mode_v2', 'ChatGPT_Image_Markdown', 'DAN_Jailbreak', 'DUDE',
  'Dan_10_0', 'Dan_11_0', 'Dan_6_0', 'Dan_6_2', 'Dan_7_0', 'Dan_8_0', 'Dan_9_0', 'STAN',
];

/** The resolver refuses longer descriptions before any screening, so longer text can't reach it. */
const MAX_CHARS = 2000;
/** Payloads shorter than this are fragments ("INJECT_HERE"), not prompts. */
const MIN_CHARS = 20;

const OUT = path.join(import.meta.dirname, '..', 'test', 'fixtures', 'injection', 'corpus.json');

async function get(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT } });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return res.text();
}

function strings(json: string): string[] {
  const parsed: unknown = JSON.parse(json);
  if (!Array.isArray(parsed)) throw new Error('expected a JSON array of prompts');
  return parsed.filter((p): p is string => typeof p === 'string');
}

/** Example payloads from the PayloadsAllTheThings page: code blocks, and inline code in bullets and tables. */
function pattPayloads(markdown: string): string[] {
  const out: string[] = [];
  // Fenced blocks of prose payloads; py/js/sql blocks are tooling, not prompts.
  for (const m of markdown.matchAll(/^[ \t]*```(\w*)[ \t]*\n([\s\S]*?)^[ \t]*```/gm)) {
    if (['', 'ps1', 'txt', 'text', 'xml', 'json', 'markdown', 'md'].includes(m[1]!)) out.push(dedent(m[2]!));
  }
  const outside = markdown.replace(/^[ \t]*```\w*[ \t]*\n[\s\S]*?^[ \t]*```/gm, '');
  for (const line of outside.split('\n')) {
    if (!/^\s*(\*|-|\|)/.test(line)) continue;
    for (const m of line.matchAll(/`([^`]+)`/g)) out.push(m[1]!);
  }
  return out;
}

function dedent(block: string): string {
  const lines = block.replace(/\s+$/, '').split('\n');
  const indent = Math.min(...lines.filter((l) => l.trim()).map((l) => l.match(/^\s*/)![0].length));
  return lines.map((l) => l.slice(indent)).join('\n');
}

function keep(texts: string[], source: string, slice: boolean): { source: string; text: string }[] {
  return texts
    .map((t) => t.trim())
    .map((t) => (slice ? t.slice(0, MAX_CHARS) : t))
    .filter((t) => t.length >= MIN_CHARS && t.length <= MAX_CHARS)
    .map((text) => ({ source, text }));
}

async function main(): Promise<void> {
  const inTheWild = strings(await get(`${GARAK}/inthewild_jailbreak_llms.json`));
  // DAN prompts run long; an attacker would cut them to fit, so they are cut here too.
  const dan = (await Promise.all(DAN_FILES.map(async (f) => strings(await get(`${GARAK}/dan/${f}.json`))))).flat();
  const patt = pattPayloads(await get(PATT));

  const seen = new Set<string>();
  const prompts = [...keep(inTheWild, 'garak/inthewild', false), ...keep(dan, 'garak/dan', true), ...keep(patt, 'payloadsallthethings', false)].filter((p) => {
    const key = p.text.toLowerCase().replace(/\s+/g, ' ');
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  const corpus = {
    note: 'Generated by scripts/update-injection-corpus.ts; do not edit by hand.',
    sources: [
      { name: 'garak/inthewild', url: `${GARAK}/inthewild_jailbreak_llms.json`, license: 'Apache-2.0', copyright: 'NVIDIA Corporation and garak contributors' },
      { name: 'garak/dan', url: `${GARAK}/dan/`, license: 'Apache-2.0', copyright: 'NVIDIA Corporation and garak contributors' },
      { name: 'payloadsallthethings', url: PATT, license: 'MIT', copyright: 'Swissky and PayloadsAllTheThings contributors' },
    ],
    prompts,
  };
  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(OUT, `${JSON.stringify(corpus, null, 1)}\n`);
  const counts = Object.groupBy(prompts, (p) => p.source);
  console.log(`wrote ${prompts.length} prompts: ${Object.entries(counts).map(([s, ps]) => `${s} ${ps!.length}`).join(', ')}`);
}

await main();
